### ISSUE TITLE
xattr -l file crashes with UnicodeDecodeError regardless whether file has xattr or not

### ISSUE THREAD

**Issue by porg** [xattr/xattr#105]
## Reproduction

```
$ echo "File L0: Created on Linux NAS. No xattr." > L0.txt
$ xattr -l L0.txt 
Traceback (most recent call last):
  File "/usr/bin/xattr", line 33, in <module>
    sys.exit(load_entry_point('xattr==0.9.7', 'console_scripts', 'xattr')())
  File "/usr/lib/python3/dist-packages/xattr/tool.py", line 196, in main
    attr_value = attr_value.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 8: invalid start byte

$ echo "File L1: Created on Linux NAS. With custom xattr." > L1.txt

$ xattr -w user.myVar HiFromLinux L1.txt 

$ xattr -l L1.txt 
Traceback (most recent call last):
  File "/usr/bin/xattr", line 33, in <module>
    sys.exit(load_entry_point('xattr==0.9.7', 'console_scripts', 'xattr')())
  File "/usr/lib/python3/dist-packages/xattr/tool.py", line 196, in main
    attr_value = attr_value.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 8: invalid start byte
```

## Environment
- OpenMediaVault 6.0.31-2 "Shaitan"
- Based on Debian 11 Bullseye (for Armbian, specially for single board computers)
- Kernel Linux 4.14.222-odroidxu4
- xattr 0.9.7-1+b1  assumingly. Has no --version argument so I searched in dpkg:
```
dpkg -l | grep xattr
ii  python3-xattr  0.9.7-1+b1 armhf
ii  xattr          0.9.7-1+b1 armhf
```

**Comment by porg** [comment]
- What was the cause and how/where was this fixed?
- In which version is this supposed to work again?

I’d appreciate an answer, thanks!

**Comment by etrepum** [comment]
Just getting a fresh start on issues, feel free to re-open if you can reproduce with the latest version.
