### ISSUE TITLE
"tool.py" chokes on MacOS/Windows EAs, when called using "xattr -l"

### ISSUE THREAD

**Issue by vmlemon** [xattr/xattr#122]
It took some effort, to track down the actual project (I assume, this one), that supplies /usr/lib/python3/dist-packages/xattr/tool.py, used by the "/usr/bin/xattr" command, that ships in the Ubuntu repositories (I guess someone else, is in charge of working on that script?), so thanks, for the tireless effort, to maintain it. 

That said, when trying to run "xattr -l", on a file from a mounted Restic repository, that was archived from a Windows system, it appears that the library chokes, on data in an attribute value, when trying to hexdump it:

```
root@DESKTOP-6HH5CK9:/tmp/1# xattr -l hosts/DESKTOP-6HH5CK9/latest/C/Windows/System32/ntoskrnl.exe
$CI.CATALOGHINT:
0000   01 00 61 00 4D 69 63 72 6F 73 6F 66 74 2D 57 69    ..a.Microsoft-Wi
0010   6E 64 6F 77 73 2D 43 6C 69 65 6E 74 2D 44 65 73    ndows-Client-Des
0020   6B 74 6F 70 2D 52 65 71 75 69 72 65 64 2D 50 61    ktop-Required-Pa
0030   63 6B 61 67 65 30 35 31 39 7E 33 31 62 66 33 38    ckage0519~31bf38
0040   35 36 61 64 33 36 34 65 33 35 7E 61 6D 64 36 34    56ad364e35~amd64
0050   7E 7E 31 30 2E 30 2E 32 32 36 32 31 2E 34 34 36    ~~10.0.22621.446
0060   30 2E 63 61 74                                     0.cat

Traceback (most recent call last):
  File "/usr/bin/xattr", line 33, in <module>
    sys.exit(load_entry_point('xattr==0.9.7', 'console_scripts', 'xattr')())
  File "/usr/lib/python3/dist-packages/xattr/tool.py", line 196, in main
    attr_value = attr_value.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf7 in position 10: invalid start byte
```
I've also seen similar, with files from MacOS, although I can't find any, in a quick search.

**Comment by jmberg** [comment]
Dup of #90, I think?
