### ISSUE TITLE
xattr has PyInstaller compatibility?

### ISSUE THREAD

**Issue by KengoSawa2** [xattr/xattr#49]
Hi all.
Thank you great and useful library.

I want to build my program with xattr by PyInstaller(3.2)
PyInstaller build success.
But,I have error when my app launched.

Error detail is below:

>Failed to execute script RapidPack
Traceback (most recent call last):
  File "RapidPack.py", line 16, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages/xattr/__init__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages/xattr/lib.py", line 596, in <module>
  File "site-packages/cffi/api.py", line 450, in verify
  File "site-packages/cffi/verifier.py", line 113, in load_library
  File "site-packages/cffi/verifier.py", line 210, in _compile_module
  File "site-packages/cffi/ffiplatform.py", line 29, in compile
  File "site-packages/cffi/ffiplatform.py", line 55, in _build
  File "distutils/dist.py", line 973, in run_command
  File "distutils/cmd.py", line 107, in ensure_finalized
  File "distutils/command/build_ext.py", line 137, in finalize_options
  File "distutils/cmd.py", line 286, in set_undefined_options
  File "distutils/dist.py", line 846, in get_command_obj
  File "distutils/dist.py", line 832, in get_command_class
distutils.errors.DistutilsModuleError: invalid command 'build'
<

I googled.
This problem is similar "cx_freeze comaptibility" at https://github.com/pyca/cryptography/issues/1323
Anyone Do you know the workaround for this problem?

MyEnvironment:

OSX 10.10.5
Python:3.4
PyInstaller:3.2
xattr:0.8.0
All Library installed by pip8.1.2

Regards

**Comment by etrepum** [comment]
This looks like a general problem with cffi and PyInstaller, you may want to consult with one or both of those projects to see what the workaround(s) are.

**Comment by KengoSawa2** [comment]
Thank you reply:)
well.. I understand. thank you.
I have looked PyInstaller issues. but I can't  solve this problem

I will look for cffi issues.
