### ISSUE TITLE
installation of xattr from pip with pycparser 2.15 fails

### ISSUE THREAD

**Issue by schaefi** [xattr/xattr#52]
I get the following error messages when installing xattr via:

```
pip install xattr
```

```
Collecting xattr (from -r .virtualenv.requirements.txt (line 19))

  Downloading xattr-0.8.0.tar.gz

    Complete output from command python setup.py egg_info:

    

    Installed /tmp/pip-build-k0l82obx/xattr/.eggs/cffi-1.8.3-py3.4-linux-x86_64.egg

    Searching for pycparser

    Reading https://pypi.python.org/simple/pycparser/

    Downloading https://pypi.python.org/packages/37/05/65d342ba500c6f9dbb1978e9dd01a1097530e0291003638bbef329ad4522/pycparser-2.15.tar.gz#md5=8629238be71db4d3f79b4fb1cd1397dc

    Best match: pycparser 2.15

    Processing pycparser-2.15.tar.gz

    Writing /tmp/easy_install-5d0094ay/pycparser-2.15/setup.cfg

    Running pycparser-2.15/setup.py -q bdist_egg --dist-dir /tmp/easy_install-5d0094ay/pycparser-2.15/egg-dist-tmp-vtpnieu3

    warning: no previously-included files matching 'yacctab.*' found under directory 'tests'

    warning: no previously-included files matching 'lextab.*' found under directory 'tests'

    warning: no previously-included files matching 'yacctab.*' found under directory 'examples'

    warning: no previously-included files matching 'lextab.*' found under directory 'examples'

    zip_safe flag not set; analyzing archive contents...

    pycparser.ply.__pycache__.ygen.cpython-34: module references __file__

    pycparser.ply.__pycache__.yacc.cpython-34: module references __file__

    pycparser.ply.__pycache__.yacc.cpython-34: module MAY be using inspect.getsourcefile

    pycparser.ply.__pycache__.yacc.cpython-34: module MAY be using inspect.stack

    pycparser.ply.__pycache__.lex.cpython-34: module references __file__

    pycparser.ply.__pycache__.lex.cpython-34: module MAY be using inspect.getsourcefile

    creating /tmp/pip-build-k0l82obx/xattr/.eggs/pycparser-2.15-py3.4.egg

    Extracting pycparser-2.15-py3.4.egg to /tmp/pip-build-k0l82obx/xattr/.eggs

    

    Installed /tmp/pip-build-k0l82obx/xattr/.eggs/pycparser-2.15-py3.4.egg

    running egg_info

    creating pip-egg-info/xattr.egg-info

    writing entry points to pip-egg-info/xattr.egg-info/entry_points.txt

    writing dependency_links to pip-egg-info/xattr.egg-info/dependency_links.txt

    writing requirements to pip-egg-info/xattr.egg-info/requires.txt

    writing pip-egg-info/xattr.egg-info/PKG-INFO

    writing top-level names to pip-egg-info/xattr.egg-info/top_level.txt

    writing manifest file 'pip-egg-info/xattr.egg-info/SOURCES.txt'

    warning: manifest_maker: standard file '-c' not found

    

    Traceback (most recent call last):

      File "<string>", line 1, in <module>

      File "/tmp/pip-build-k0l82obx/xattr/setup.py", line 67, in <module>

        cmdclass={'build': cffi_build},

      File "/opt/python/3.4.4/lib/python3.4/distutils/core.py", line 148, in setup

        dist.run_commands()

      File "/opt/python/3.4.4/lib/python3.4/distutils/dist.py", line 955, in run_commands

        self.run_command(cmd)

      File "/opt/python/3.4.4/lib/python3.4/distutils/dist.py", line 974, in run_command

        cmd_obj.run()

      File "/home/travis/build/SUSE/kiwi/.tox/3.4/lib/python3.4/site-packages/setuptools/command/egg_info.py", line 279, in run

        self.find_sources()

      File "/home/travis/build/SUSE/kiwi/.tox/3.4/lib/python3.4/site-packages/setuptools/command/egg_info.py", line 306, in find_sources

        mm.run()

      File "/home/travis/build/SUSE/kiwi/.tox/3.4/lib/python3.4/site-packages/setuptools/command/egg_info.py", line 533, in run

        self.add_defaults()

      File "/home/travis/build/SUSE/kiwi/.tox/3.4/lib/python3.4/site-packages/setuptools/command/egg_info.py", line 562, in add_defaults

        sdist.add_defaults(self)

      File "/home/travis/build/SUSE/kiwi/.tox/3.4/lib/python3.4/site-packages/setuptools/command/py36compat.py", line 34, in add_defaults

        self._add_defaults_python()

      File "/home/travis/build/SUSE/kiwi/.tox/3.4/lib/python3.4/site-packages/setuptools/command/sdist.py", line 131, in _add_defaults_python

        build_py = self.get_finalized_command('build_py')

      File "/opt/python/3.4.4/lib/python3.4/distutils/cmd.py", line 299, in get_finalized_command

        cmd_obj.ensure_finalized()

      File "/opt/python/3.4.4/lib/python3.4/distutils/cmd.py", line 107, in ensure_finalized

        self.finalize_options()

      File "/home/travis/build/SUSE/kiwi/.tox/3.4/lib/python3.4/site-packages/setuptools/command/build_py.py", line 34, in finalize_options

        orig.build_py.finalize_options(self)

      File "/opt/python/3.4.4/lib/python3.4/distutils/command/build_py.py", line 45, in finalize_options

        ('force', 'force'))

      File "/opt/python/3.4.4/lib/python3.4/distutils/cmd.py", line 287, in set_undefined_options

        src_cmd_obj.ensure_finalized()

      File "/opt/python/3.4.4/lib/python3.4/distutils/cmd.py", line 107, in ensure_finalized

        self.finalize_options()

      File "/tmp/pip-build-k0l82obx/xattr/setup.py", line 15, in finalize_options

        from xattr.lib import ffi

      File "/tmp/pip-build-k0l82obx/xattr/xattr/__init__.py", line 12, in <module>

        from .lib import (XATTR_NOFOLLOW, XATTR_CREATE, XATTR_REPLACE,

      File "/tmp/pip-build-k0l82obx/xattr/xattr/lib.py", line 26, in <module>

        """)

      File "/tmp/pip-build-k0l82obx/xattr/.eggs/cffi-1.8.3-py3.4-linux-x86_64.egg/cffi/api.py", line 105, in cdef

        self._cdef(csource, override=override, packed=packed)

      File "/tmp/pip-build-k0l82obx/xattr/.eggs/cffi-1.8.3-py3.4-linux-x86_64.egg/cffi/api.py", line 119, in _cdef

        self._parser.parse(csource, override=override, **options)

      File "/tmp/pip-build-k0l82obx/xattr/.eggs/cffi-1.8.3-py3.4-linux-x86_64.egg/cffi/cparser.py", line 299, in parse

        self._internal_parse(csource)

      File "/tmp/pip-build-k0l82obx/xattr/.eggs/cffi-1.8.3-py3.4-linux-x86_64.egg/cffi/cparser.py", line 304, in _internal_parse

        ast, macros, csource = self._parse(csource)

      File "/tmp/pip-build-k0l82obx/xattr/.eggs/cffi-1.8.3-py3.4-linux-x86_64.egg/cffi/cparser.py", line 260, in _parse

        ast = _get_parser().parse(csource)

      File "/tmp/pip-build-k0l82obx/xattr/.eggs/cffi-1.8.3-py3.4-linux-x86_64.egg/cffi/cparser.py", line 40, in _get_parser

        _parser_cache = pycparser.CParser()

      File "/tmp/pip-build-k0l82obx/xattr/.eggs/pycparser-2.15-py3.4.egg/pycparser/c_parser.py", line 87, in __init__

        outputdir=taboutputdir)

      File "/tmp/pip-build-k0l82obx/xattr/.eggs/pycparser-2.15-py3.4.egg/pycparser/c_lexer.py", line 66, in build

        self.lexer = lex.lex(object=self, **kwargs)

      File "/tmp/pip-build-k0l82obx/xattr/.eggs/pycparser-2.15-py3.4.egg/pycparser/ply/lex.py", line 911, in lex

        lexobj.readtab(lextab, ldict)

      File "/tmp/pip-build-k0l82obx/xattr/.eggs/pycparser-2.15-py3.4.egg/pycparser/ply/lex.py", line 233, in readtab

        titem.append((re.compile(pat, lextab._lexreflags | re.VERBOSE), _names_to_funcs(func_name, fdict)))

      File "/home/travis/build/SUSE/kiwi/.tox/3.4/lib/python3.4/re.py", line 223, in compile

        return _compile(pattern, flags)

      File "/home/travis/build/SUSE/kiwi/.tox/3.4/lib/python3.4/re.py", line 294, in _compile

        p = sre_compile.compile(pattern, flags)

      File "/home/travis/build/SUSE/kiwi/.tox/3.4/lib/python3.4/sre_compile.py", line 579, in compile

        "sorry, but this version only supports 100 named groups"

    AssertionError: sorry, but this version only supports 100 named groups

    

    ----------------------------------------
```

**Comment by schaefi** [comment]
with pycparser 2.14 everything is fine

**Comment by alex** [comment]
This was a bug with pycaparser 2.15, either .14 or .16 fixes it.
