### ISSUE TITLE
surrogateescape not present on python2

### ISSUE THREAD

**Issue by jmgurney** [xattr/xattr#59]
When trying to run the tests on python 2, I get an error that surrogateescape is not present.

I have a fix for this in my branch, py2compat, but I haven't issued a pull request as the main upstream project is broken, and I've submitted a fix for them.

**Comment by jmgurney** [comment]
commit is:
SHA: ffc74126465ad0976631b69a3d8857a6e379c29d

**Comment by jmgurney** [comment]
commit is jmgurney/py2compat@ffc74126465ad0976631b69a3d8857a6e379c29d

**Comment by jmgurney** [comment]
commit is jmgurney/xattr@py2compat

**Comment by jmgurney** [comment]
commit is: ffc74126465ad0976631b69a3d8857a6e379c29d

**Comment by etrepum** [comment]
I've added a simpler workaround for now. When surrogateescape is not present, then it will use strict error handling. https://github.com/xattr/xattr/blob/master/xattr/compat.py#L16-L31

**Comment by novel** [comment]
@etrepum as `sys.getfilesystemencoding()` return value is based on user's locale, this produces different results for different environments.

With unicode locale things work fine. With C locale tests fail like this:

```
$  LC_ALL=C python setup.py test
...
======================================================================
ERROR: test_attr (xattr.tests.test_xattr.TestFile)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/home/novel/ports_stuff/py-xattr/work-py27/xattr-0.9.3/xattr/tests/test_xattr.py", line 37, in test_attr
    x[u'user.\N{SNOWMAN}'] = b'not a snowman'
  File "/usr/home/novel/ports_stuff/py-xattr/work-py27/xattr-0.9.3/xattr/__init__.py", line 112, in __setitem__
    self.set(item, value)
  File "/usr/home/novel/ports_stuff/py-xattr/work-py27/xattr-0.9.3/xattr/__init__.py", line 78, in set
    return self._call(_setxattr, _fsetxattr, name, value, 0, options | self.options)
  File "/usr/home/novel/ports_stuff/py-xattr/work-py27/xattr-0.9.3/xattr/__init__.py", line 58, in _call
    return fd_func(self.value, *args)
  File "/usr/home/novel/ports_stuff/py-xattr/work-py27/xattr-0.9.3/xattr/lib.py", line 90, in _fsetxattr
    name = fs_encode(name)
  File "/usr/home/novel/ports_stuff/py-xattr/work-py27/xattr-0.9.3/xattr/compat.py", line 31, in fs_encode
    return val.encode(fs_encoding, fs_errors)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2603' in position 5: ordinal not in range(128)
```

I'm wondering if it'd be a good thing to introduce some general error/exception that tells a user that their locale settings doesn't allow using unicode values, and update the unit test suite to run tests using Unicode locale and also run tests using C locale and check that the encoding error pops up in this case?

**Comment by etrepum** [comment]
I think that the right thing to do here is whatever the stdlib does when those functions encounter paths that can not be represented in the given environment. What does `os.path.exists` do with such a path in that scenario, for example?

**Comment by novel** [comment]
`os.path.exists` appears to just throw `UnicodeEncodeError`. Tested with the following snippet:

```
#!/usr/bin/env python2                                                                                                                                                                                             
# coding: utf-8                                                                                                                                                                                                    
                                                                                                                                                                                                                   
import os.path                                                                                                                                                                                                     
                                                                                                                                                                                                                   
if __name__ == "__main__":                                                                                                                                                                                         
    fname = u'/tmp/тест'                                                                                                                                                                                           
    print os.path.exists(fname)
```

```
$ ./fstest.py                                                                                                                                                                             
True                                                                                                                                                                                                               
[21837 refs]                                                                                                                                                                                                       
$ LC_ALL=C ./fstest.py                                                                                                                                                                    
Traceback (most recent call last):                                                                                                                                                                                 
  File "./fstest.py", line 8, in <module>                                                                                                                                                                          
    print os.path.exists(fname)                                                                                                                                                                                    
  File "/usr/local/lib/python2.7/genericpath.py", line 26, in exists                                                                                                                                               
    os.stat(path)                                                                                                                                                                                                  
UnicodeEncodeError: 'ascii' codec can't encode characters in position 5-8: ordinal not in range(128)                                                                                                               
[21850 refs]                                                                                                                                                                                                       
$
```

**Comment by etrepum** [comment]
Seems like the current behavior is the least surprising.

**Comment by novel** [comment]
> Seems like the current behavior is the least surprising.

What would be your suggestion on that?

I'm not sure if we can do anything about that, but it'd be good to make unit test results not to depend on environment.

**Comment by etrepum** [comment]
Pull request to do that would be accepted for sure
