### ISSUE TITLE
`xattr().update()` does not work in Python 3

### ISSUE THREAD

**Issue by toriningen** [xattr/xattr#86]
If you create a file `kek.txt` and try to add multiple attributes via dict-like `xattr()` interface, this library would try to use `.iteritems()`, which is not available on dicts in Python 3:
```
>>> xattr.xattr('kek.txt').update({'foo': b'FOO', 'bar': b'BAR'})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../venv/lib/python3.7/site-packages/xattr/__init__.py", line 142, in update
    for k, v in seq.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'
```
I am using `xattr (0.9.6)`.

**Comment by etrepum** [comment]
This should be resolved in 0.9.7
