### ISSUE TITLE
xattr unicode error decoding _values_

### ISSUE THREAD

**Issue by xdgc** [xattr/xattr#90]
When a filesystem extended attribute has been set to a binary value, the `xattr` program cannot display it. `xattr` appears to assume that `xattr` values are utf-8-encoded text, but there is no such requirement of xattrs. The underlying python library seems to support the attributes but the executable tool does not.

Here's an example:

```
[2882/1]$ xattr example.txt
Traceback (most recent call last):
  File "/usr/bin/xattr", line 11, in <module>
    load_entry_point('xattr==0.9.6', 'console_scripts', 'xattr')()
  File "/usr/lib/python3/dist-packages/xattr/tool.py", line 196, in main
    attr_value = attr_value.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9a in position 33: invalid start byte
[2883/1]$ getfattr --dump example.txt
# file: example.txt
user.DosStream.com.apple.metadata_kMDItemUserTags:$DATA=0sYnBsaXN0MDCiAQJWQmx1ZQo0U2ZvbwgLEgAAAAAAAAEBAAAAAAAAAAMAAAAAAAAAAAAAAAAAAAAWAA==
user.org.netatalk.Metadata=0sAAUWBwACAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAEAAAAmgAAAAAAAAAIAAABYgAAABAAAAAJAAAAegAAACAAAAAOAAABcgAAAASAREVWAAABdgAAAACASU5PAAABfgAAAACAU1lOAAABhgAAAACAU1Z+AAABjgAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJsRzPCbEczyAAAAAJsRzPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
```

(The getfattr tool encodes binary values as base64 internally.)

Corrective action: the xattr tool should attempt utf-8 decoding, then fall back on other decodings that might make sense in context and finally just display the binary value.

**Comment by xdgc** [comment]
Note that this differs from #82 in that it's values concerned here, not names.

**Comment by darkhaniop** [comment]
I just encountered a similar problem on a rock64 SBC running Debian Stretch.

I don't know if this is a proper solution, but after the following modification in `xattr/tool.py`, I was able to execute `xattr`:
```python
                    try:
                        attr_value = decompress(attrs[attr_name])
                    except zlib.error:
                        attr_value = attrs[attr_name]
                    attr_value = attr_value.decode('unicode_escape')  # <-- modified from `attr_value = attr_value.decode('utf-8')`
```

**Setup info**

`xattr` was installed with:
```
# apt install xattr
...
Get:1 http://httpredir.debian.org/debian stretch/main arm64 python3-cffi-backend arm64 1.9.1-2 [64.2 kB]
Get:2 http://httpredir.debian.org/debian stretch/main arm64 python3-ply all 3.9-1 [64.4 kB]
Get:3 http://httpredir.debian.org/debian stretch/main arm64 python3-pycparser all 2.17-2 [63.4 kB]
Get:4 http://httpredir.debian.org/debian stretch/main arm64 python3-cffi all 1.9.1-2 [73.4 kB]
Get:5 http://httpredir.debian.org/debian stretch/main arm64 python3-pkg-resources all 33.1.1-1 [137 kB]
Get:6 http://httpredir.debian.org/debian stretch/main arm64 python3-xattr arm64 0.9.1-1 [17.6 kB]
Get:7 http://httpredir.debian.org/debian stretch/main arm64 xattr arm64 0.9.1-1 [6158 B]
...
```

Before the above fix, running `xattr` gave the following error:
```
Traceback (most recent call last):
  File "/usr/bin/xattr", line 11, in <module>
    load_entry_point('xattr==0.9.1', 'console_scripts', 'xattr')()
  File "/usr/lib/python3/dist-packages/xattr/tool.py", line 188, in main
    attr_value = attr_value.decode('utf-8')
```

**Comment by TianyiShi2001** [comment]
I encountered the same problem when I used non-english tags on Mac and `rsync`ed the file to the linux system. When I `rsync`ed the file back to the Mac the tags were displayed normally.

Indeed, the Mac tags (`com.apple.metadata:_kMDItemUserTags`) are not utf-8 encoded at all, and when I use `xattr -p com.apple.metadata:_kMDItemUserTags some_file` a bytestream is outputted.
