### ISSUE TITLE
xattr not installing via pip with m1 macintosh

### ISSUE THREAD

**Issue by bschollnick** [xattr/xattr#91]
setuptools 41.2.0 51.0.0 wheel
wheel 0.33.1 0.36.1 wheel

Pip 20.3.1
Python 3.8
Big Sur 11.0.1 (Apple M1)

Description

Clean install with Python 3.8.2, installed virtualenv, and trying to install various modules.
Specifically in this case xattr.

loading Xattr via pip results in this exception report:

'''
Collecting xattr
  Using cached xattr-0.9.7.tar.gz (13 kB)
    ERROR: Command errored out with exit status 1:
     command: /Library/Developer/CommandLineTools/usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/6g/0vldjqgd5d55rdv163phqh6r0000gn/T/pip-install-jncbjfpu/xattr_08a31bc4fb204d82a4d62457ddff34ba/setup.py'"'"'; __file__='"'"'/private/var/folders/6g/0vldjqgd5d55rdv163phqh6r0000gn/T/pip-install-jncbjfpu/xattr_08a31bc4fb204d82a4d62457ddff34ba/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/6g/0vldjqgd5d55rdv163phqh6r0000gn/T/pip-pip-egg-info-798hcrbo
         cwd: /private/var/folders/6g/0vldjqgd5d55rdv163phqh6r0000gn/T/pip-install-jncbjfpu/xattr_08a31bc4fb204d82a4d62457ddff34ba/
    Complete output (167 lines):
    c/_cffi_backend.c:5887:16: warning: comparison of integers of different signs: 'ffi_status' and 'int' [-Wsign-compare]
        if (status == -1) {
            ~~~~~~ ^  ~~
    1 warning generated.
    c/_cffi_backend.c:5887:16: warning: comparison of integers of different signs: 'ffi_status' and 'int' [-Wsign-compare]
        if (status == -1) {
            ~~~~~~ ^  ~~
    1 warning generated.
    Traceback (most recent call last):
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 172, in run
        cmd = self.call_command('install_lib', warn_dir=0)
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 158, in call_command
        self.run_command(cmdname)
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/command/install_lib.py", line 15, in run
        self.byte_compile(outfiles)
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/command/install_lib.py", line 132, in byte_compile
        byte_compile(files, optimize=0,
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/util.py", line 466, in byte_compile
        compile(file, cfile, dfile)
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/py_compile.py", line 157, in compile
        os.makedirs(dirname)
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/os.py", line 213, in makedirs
        makedirs(head, exist_ok=exist_ok)
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/os.py", line 213, in makedirs
        makedirs(head, exist_ok=exist_ok)
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/os.py", line 213, in makedirs
        makedirs(head, exist_ok=exist_ok)
      [Previous line repeated 2 more times]
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/os.py", line 223, in makedirs
        mkdir(name, mode)
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/sandbox.py", line 310, in wrap
        path = self._remap_input(name, path, *args, **kw)
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/sandbox.py", line 452, in _remap_input
        self._violation(operation, os.path.realpath(path), *args, **kw)
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/sandbox.py", line 407, in _violation
        raise SandboxViolation(operation, args, kw)
    setuptools.sandbox.SandboxViolation: SandboxViolation: mkdir('/Users/benjamin/Library/Caches/com.apple.python/private/var/folders/6g/0vldjqgd5d55rdv163phqh6r0000gn/T/easy_install-259hw_9z', 511) {}
    
    The package setup script has attempted to modify files on your system
    that are not within the EasyInstall build area, and has been aborted.
    
    This package cannot be safely installed by EasyInstall, and may not
    support alternate installation locations even if you run its setup
    script by hand.  Please inform the package's author and the EasyInstall
    maintainers to find out if a fix or workaround is available.
    
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/var/folders/6g/0vldjqgd5d55rdv163phqh6r0000gn/T/easy_install-259hw_9z/cffi-1.14.4/setup.py", line 179, in <module>
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/core.py", line 163, in setup
        raise SystemExit("error: " + str(msg))
    SystemExit: error: SandboxViolation: mkdir('/Users/benjamin/Library/Caches/com.apple.python/private/var/folders/6g/0vldjqgd5d55rdv163phqh6r0000gn/T/easy_install-259hw_9z', 511) {}
    
    The package setup script has attempted to modify files on your system
    that are not within the EasyInstall build area, and has been aborted.
    
    This package cannot be safely installed by EasyInstall, and may not
    support alternate installation locations even if you run its setup
    script by hand.  Please inform the package's author and the EasyInstall
    maintainers to find out if a fix or workaround is available.
    
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 1144, in run_setup
        run_setup(setup_script, args)
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/sandbox.py", line 253, in run_setup
        raise
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/contextlib.py", line 131, in __exit__
        self.gen.throw(type, value, traceback)
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/contextlib.py", line 131, in __exit__
        self.gen.throw(type, value, traceback)
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/sandbox.py", line 166, in save_modules
        saved_exc.resume()
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/sandbox.py", line 141, in resume
        six.reraise(type, exc, self._tb)
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/_vendor/six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/var/folders/6g/0vldjqgd5d55rdv163phqh6r0000gn/T/easy_install-259hw_9z/cffi-1.14.4/setup.py", line 179, in <module>
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/core.py", line 163, in setup
        raise SystemExit("error: " + str(msg))
    SystemExit: error: SandboxViolation: mkdir('/Users/benjamin/Library/Caches/com.apple.python/private/var/folders/6g/0vldjqgd5d55rdv163phqh6r0000gn/T/easy_install-259hw_9z', 511) {}
    
    The package setup script has attempted to modify files on your system
    that are not within the EasyInstall build area, and has been aborted.
    
    This package cannot be safely installed by EasyInstall, and may not
    support alternate installation locations even if you run its setup
    script by hand.  Please inform the package's author and the EasyInstall
    maintainers to find out if a fix or workaround is available.
    
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/6g/0vldjqgd5d55rdv163phqh6r0000gn/T/pip-install-jncbjfpu/xattr_08a31bc4fb204d82a4d62457ddff34ba/setup.py", line 34, in <module>
        setup(
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/dist.py", line 716, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 780, in resolve
        dist = best[req.key] = env.best_match(
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1065, in best_match
        return self.obtain(req, installer)
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1077, in obtain
        return installer(requirement)
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/dist.py", line 786, in fetch_build_egg
        return cmd.easy_install(req)
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 679, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 705, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 890, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 1158, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 1146, in run_setup
        raise DistutilsError("Setup script exited with %s" % (v.args[0],))
    distutils.errors.DistutilsError: Setup script exited with error: SandboxViolation: mkdir('/Users/benjamin/Library/Caches/com.apple.python/private/var/folders/6g/0vldjqgd5d55rdv163phqh6r0000gn/T/easy_install-259hw_9z', 511) {}
    
    The package setup script has attempted to modify files on your system
    that are not within the EasyInstall build area, and has been aborted.
    
    This package cannot be safely installed by EasyInstall, and may not
    support alternate installation locations even if you run its setup
    script by hand.  Please inform the package's author and the EasyInstall
    maintainers to find out if a fix or workaround is available.
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
'''

If I download xattr, and manually import it (after installing CFFI), everything seems to work fine (at least via rosetta 2).  I haven't tried that in M1 native yet.

**Comment by etrepum** [comment]
I don't have access to an M1 mac, but perhaps the version bounds on cffi have to be updated? I'll give that a shot.

**Comment by bschollnick** [comment]
Okay, I did some checking.  And there definitely is some issues going on here...  But it's changed since I last posted...

When under rosetta 2:

```Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: cffi in /Users/benjamin/Library/Python/3.8/lib/python/site-packages (1.14.4)
Requirement already satisfied: pycparser in /Users/benjamin/Library/Python/3.8/lib/python/site-packages (from cffi) (2.20)
benjamin@Nerv xattr-master % pip install xattr
Defaulting to user installation because normal site-packages is not writeable
Collecting xattr
  Using cached xattr-0.9.7.tar.gz (13 kB)
    ERROR: Command errored out with exit status 1:
     command: /Library/Developer/CommandLineTools/usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/6g/0vldjqgd5d55rdv163phqh6r0000gn/T/pip-install-qjddqki7/xattr_ab178340b995402b92377061d7a424cf/setup.py'"'"'; __file__='"'"'/private/var/folders/6g/0vldjqgd5d55rdv163phqh6r0000gn/T/pip-install-qjddqki7/xattr_ab178340b995402b92377061d7a424cf/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/6g/0vldjqgd5d55rdv163phqh6r0000gn/T/pip-pip-egg-info-mvqzt139
         cwd: /private/var/folders/6g/0vldjqgd5d55rdv163phqh6r0000gn/T/pip-install-qjddqki7/xattr_ab178340b995402b92377061d7a424cf/
    Complete output (28 lines):
    Warning: 'classifiers' should be a list, got type 'filter'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/6g/0vldjqgd5d55rdv163phqh6r0000gn/T/pip-install-qjddqki7/xattr_ab178340b995402b92377061d7a424cf/setup.py", line 34, in <module>
        setup(
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/dist.py", line 445, in __init__
        _Distribution.__init__(self, {
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 292, in __init__
        self.finalize_options()
      File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/dist.py", line 734, in finalize_options
        ep.load()(self, ep.name, value)
      File "/Users/benjamin/Library/Python/3.8/lib/python/site-packages/cffi/setuptools_ext.py", line 219, in cffi_modules
        add_cffi_module(dist, cffi_module)
      File "/Users/benjamin/Library/Python/3.8/lib/python/site-packages/cffi/setuptools_ext.py", line 49, in add_cffi_module
        execfile(build_file_name, mod_vars)
      File "/Users/benjamin/Library/Python/3.8/lib/python/site-packages/cffi/setuptools_ext.py", line 25, in execfile
        exec(code, glob, glob)
      File "xattr/lib_build.py", line 12, in <module>
        ffi = FFI()
      File "/Users/benjamin/Library/Python/3.8/lib/python/site-packages/cffi/api.py", line 48, in __init__
        import _cffi_backend as backend
    ImportError: dlopen(/Users/benjamin/Library/Python/3.8/lib/python/site-packages/_cffi_backend.cpython-38-darwin.so, 2): no suitable image found.  Did find:
    	/Users/benjamin/Library/Python/3.8/lib/python/site-packages/_cffi_backend.cpython-38-darwin.so: mach-o, but wrong architecture
    	/Users/benjamin/Library/Python/3.8/lib/python/site-packages/_cffi_backend.cpython-38-darwin.so: mach-o, but wrong architecture
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Please note, I already have CFFI installed via PIP.  So I'm not sure what's happening here...

Definitely see architecture statements, so...  

Under M1 Native:

- If CFFI is not installed:

```
(downloader) benjamin@Nerv dropbox % pip install xattr
Collecting xattr
  Using cached xattr-0.9.7.tar.gz (13 kB)
    ERROR: Command errored out with exit status 1:
     command: /Users/benjamin/venvs/downloader/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/6g/0vldjqgd5d55rdv163phqh6r0000gn/T/pip-install-7aidq3ae/xattr_a0a43bfba55d4f789227c7a2e892bfce/setup.py'"'"'; __file__='"'"'/private/var/folders/6g/0vldjqgd5d55rdv163phqh6r0000gn/T/pip-install-7aidq3ae/xattr_a0a43bfba55d4f789227c7a2e892bfce/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/6g/0vldjqgd5d55rdv163phqh6r0000gn/T/pip-pip-egg-info-lpnyjxlj
         cwd: /private/var/folders/6g/0vldjqgd5d55rdv163phqh6r0000gn/T/pip-install-7aidq3ae/xattr_a0a43bfba55d4f789227c7a2e892bfce/
    Complete output (44 lines):
    WARNING: The wheel package is not available.
      ERROR: Command errored out with exit status 1:
       command: /Users/benjamin/venvs/downloader/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/6g/0vldjqgd5d55rdv163phqh6r0000gn/T/pip-wheel-p2ob1zlw/cffi_bc0af8bb9c94471bada3577b7cf33d0c/setup.py'"'"'; __file__='"'"'/private/var/folders/6g/0vldjqgd5d55rdv163phqh6r0000gn/T/pip-wheel-p2ob1zlw/cffi_bc0af8bb9c94471bada3577b7cf33d0c/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/6g/0vldjqgd5d55rdv163phqh6r0000gn/T/pip-wheel-vt3k2gxx
           cwd: /private/var/folders/6g/0vldjqgd5d55rdv163phqh6r0000gn/T/pip-wheel-p2ob1zlw/cffi_bc0af8bb9c94471bada3577b7cf33d0c/
      Complete output (6 lines):
      usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
         or: setup.py --help [cmd1 cmd2 ...]
         or: setup.py --help-commands
         or: setup.py cmd --help
    
      error: invalid command 'bdist_wheel'
      ----------------------------------------
      ERROR: Failed building wheel for cffi
    ERROR: Failed to build one or more wheels
    Traceback (most recent call last):
      File "/Users/benjamin/venvs/downloader/lib/python3.8/site-packages/setuptools/installer.py", line 126, in fetch_build_egg
        subprocess.check_call(cmd)
      File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/Users/benjamin/venvs/downloader/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/folders/6g/0vldjqgd5d55rdv163phqh6r0000gn/T/tmptvu0aeoq', '--quiet', 'cffi>=1.0.0']' returned non-zero exit status 1.
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/6g/0vldjqgd5d55rdv163phqh6r0000gn/T/pip-install-7aidq3ae/xattr_a0a43bfba55d4f789227c7a2e892bfce/setup.py", line 34, in <module>
        setup(
      File "/Users/benjamin/venvs/downloader/lib/python3.8/site-packages/setuptools/__init__.py", line 152, in setup
        _install_setup_requires(attrs)
      File "/Users/benjamin/venvs/downloader/lib/python3.8/site-packages/setuptools/__init__.py", line 147, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/Users/benjamin/venvs/downloader/lib/python3.8/site-packages/setuptools/dist.py", line 673, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "/Users/benjamin/venvs/downloader/lib/python3.8/site-packages/pkg_resources/__init__.py", line 764, in resolve
        dist = best[req.key] = env.best_match(
      File "/Users/benjamin/venvs/downloader/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1049, in best_match
        return self.obtain(req, installer)
      File "/Users/benjamin/venvs/downloader/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1061, in obtain
        return installer(requirement)
      File "/Users/benjamin/venvs/downloader/lib/python3.8/site-packages/setuptools/dist.py", line 732, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "/Users/benjamin/venvs/downloader/lib/python3.8/site-packages/setuptools/installer.py", line 128, in fetch_build_egg
        raise DistutilsError(str(e)) from e
    distutils.errors.DistutilsError: Command '['/Users/benjamin/venvs/downloader/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/folders/6g/0vldjqgd5d55rdv163phqh6r0000gn/T/tmptvu0aeoq', '--quiet', 'cffi>=1.0.0']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

If CFFI **is installed**:

(downloader) benjamin@Nerv dropbox % pip install cffi
Collecting cffi
  Using cached cffi-1.14.4.tar.gz (471 kB)
Collecting pycparser
  Using cached pycparser-2.20-py2.py3-none-any.whl (112 kB)
Using legacy 'setup.py install' for cffi, since package 'wheel' is not installed.
Installing collected packages: pycparser, cffi
    Running setup.py install for cffi ... done
Successfully installed cffi-1.14.4 pycparser-2.20
(downloader) benjamin@Nerv dropbox % pip install xattr
Collecting xattr
  Using cached xattr-0.9.7.tar.gz (13 kB)
Requirement already satisfied: cffi>=1.0.0 in /Users/benjamin/venvs/downloader/lib/python3.8/site-packages (from xattr) (1.14.4)
Requirement already satisfied: pycparser in /Users/benjamin/venvs/downloader/lib/python3.8/site-packages (from cffi>=1.0.0->xattr) (2.20)
Using legacy 'setup.py install' for xattr, since package 'wheel' is not installed.
Installing collected packages: xattr
    Running setup.py install for xattr ... done
Successfully installed xattr-0.9.7

**Comment by bschollnick** [comment]
So this appears not to be an xattr, but an xattr prerequisite issue...

**Comment by etrepum** [comment]
If it's not an issue with cffi then it's an issue with that version of Python, setuptools or pip. Not sure if there's anything we can do about that in xattr.

**Comment by giovannicoppola** [comment]
any advice on how to use xattr with an M1 mac? I am migrating and I can't run many scripts that rely on this package.

**Comment by etrepum** [comment]
You should be able to build and install it from source on an m1 mac without issue

**Comment by bschollnick** [comment]
The last time I tried, I had no issues...  Make sure that cffi has been installed before hand, but once again, I didn't have any preq issues when I recently recreated by virtualenv.

**Comment by giovannicoppola** [comment]
Thank you! I can confirm that installing cffi solved the issue.

**Comment by bschollnick** [comment]
So cffi should be added to the pre-reqs for xattr, I assume?

**Comment by etrepum** [comment]
cffi is in requirements.txt, and in setup.py (both install_requires and setup_requires). If you’re using pip or any other tool that works with requirements.txt you shouldn’t have to explicitly install cffi.
